version: '2'

services:
  # PostgreSQL
  postgres:
    image: camptocamp/postgis:9.5
    environment:
      POSTGRES_USER: sequelize_test
      POSTGRES_PASSWORD: sequelize_test
      POSTGRES_DB: sequelize_test
    volumes:
      - /mnt/sequelize-ramdisk:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:8998:5432"
    container_name: postgres

  # MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: lollerskates
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
    volumes:
      - /mnt/sequelize-ramdisk:/var/lib/mysql
    ports:
      - "127.0.0.1:8999:3306"
    container_name: mysql
